name: hermony_app
description: A community-based mobile app to empower young women in the art industry.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.1.0
  google_sign_in: ^6.3.0

  # dotenv
  flutter_dotenv: 6.0.0

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  equatable: ^2.0.7


  # -------------------------
  # UI & Utils
  # -------------------------
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images
    - assets/icons
